Change argon2 salt length to recommended value (16 bytes)
novifinancial/opaque-ke pull request #275
Opened 2022-06-08 15:23 UTC by falko17

This pull request changes the `Ksf` implementation for Argon2 and sets the salt length to 16 bytes (instead of the minimal length of 8 bytes), the value recommended for password hashing in section 3.1 of the Argon2 specification.
This also serves to improve interoperability: for example, with this change, it's possible to use `opaque-ke` in conjunction with `libopaque`, since it also uses a 16-byte salt by default.

Note that this will make existing registrations (i.e., those made with an 8-byte salt) invalid, since KSF parameters (including salt length) must stay the same across registration and login.

2022-06-09 08:51 UTC, kevinlewi commented
Given https://github.com/RustCrypto/password-hashes/pull/306, perhaps it would be more apt to use the constant newly-exported constant `RECOMMENDED_SALT_LEN`?

2022-06-10 01:21 UTC, daxpedda approved these changes
I just submitted https://github.com/RustCrypto/password-hashes/pull/307 for us. The RustCrypto team is quite quick with releasing new versions on demand.

Despite my comment before, I think the PR is still fine, we can follow-up afterwards.

2022-06-10 01:46 UTC, kevinlewi requested changes
Just need to add feature-gating for argon2

2022-06-10 06:48 UTC, falko17 commented on src/ksf.rs
> +const ARGON2_RECOMMENDED_SALT_LEN: usize = 16;
Fixed in 29c7a54.

2022-06-10 06:49 UTC, falko17 commented
Thanks for your comments! Should we wait until https://github.com/RustCrypto/password-hashes/pull/307 is merged so that the constant can be used, or do we want to address this in a follow-up PR?

2022-06-13 03:19 UTC, kevinlewi approved these changes

2022-06-13 03:19 UTC, kevinlewi commented
Agreed, we can land now. Thanks for contributing!

2022-06-13 03:19 UTC, merged